name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Google Test
      run: |
        wget https://github.com/google/googletest/archive/refs/tags/release-1.15.0.tar.gz
        tar -xzf release-1.15.0.tar.gz
        cd googletest-release-1.15.0
        mkdir build
        cd build
        cmake ..
        sudo make install
      
    - name: Set up SFML
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libsfml-dev

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ctest
